In [19]:
import requests
import json
import pandas as pd

YELP_API_KEY = YELP_API_KEY
API_ENDPOINT = 'https://api.yelp.com/v3/businesses/search'

# Yelp API endpoint URL for exploring restaurants
yelp_url = 'https://api.yelp.com/v3/businesses/search'
yelp_headers = {
    "Authorization": f"Bearer {YELP_API_KEY}"
}

venues_data_list = []

yelp_params = {
    'location': 'Merivale,Ottawa',
    'radius': 2000,  # Radius for restaurant search (adjust as needed)
    'categories': 'restaurants',
    'limit': 50,  # Number of restaurants to retrieve (adjust as needed)
    }

yelp_response = requests.get(API_ENDPOINT, params=yelp_params, headers=yelp_headers)

# Check if the Yelp response is successful
if yelp_response.status_code == 200:
    yelp_data = json.loads(yelp_response.text)
    for business in yelp_data.get('businesses', []):
        categories = [category.get('title') for category in business.get('categories', [])]
        cuisine_keywords = ['coffee','fast food', 'burgers', 'sushi', 'pizza', 'sandwiches', 'pub', 'bar','cafe','steak','seafood','dessert','beer']
        nationality_keywords = ['european','greek','african','mexican','venezuelan','vietnamese','malaysian','caribbean','persian','filipino','irish','british','scottish','ethiopian','american', 'japanese', 'mediterranean', 'thai', 'french', 'italian', 'middle eastern','canadian','asian','indian','chinese','german','korean','peruvian']
        cuisine_list = []
        nationality_list = []
        for category in categories:
            category_lower = category.lower()
            if any(keyword in category_lower for keyword in cuisine_keywords):
                cuisine_list.append(category)
            elif any(keyword in category_lower for keyword in nationality_keywords):
                nationality_list.append(category)
        restaurant_details = {
            'Name': business.get('name'),
            'Categories': ', '.join(categories),
            'Cuisine Types': ', '.join(cuisine_list),
            'Nationalities': ', '.join(nationality_list),
            'Rating': business.get('rating'),
            'Address': ', '.join([business.get('location', {}).get('address1'), business.get('location', {}).get('city')]) or 'N/A',
            'Res_Latitude': business.get('coordinates', {}).get('latitude'),
            'Res_Longitude': business.get('coordinates', {}).get('longitude'),
            'Reviews': business.get('review_count'),
            'Distance': business.get('distance'),
            'Phone': business.get('phone') or 'N/A',
            'Closed': business.get('is_closed'),
            'Price': business.get('price') or 'N/A',
        }
        venues_data_list.append(restaurant_details)

# Create a DataFrame from the restaurant data list
Merivale = pd.DataFrame(venues_data_list)


Merivale.shape

(50, 13)

In [22]:
Ottawa_df = pd.concat([old,
Carlington,
Westboro,
Urbandale,
Vanier,
Alta,
Pineview,
Crestview,
Fisher,
Tanglewood,
Bayshore,
Centretown,
Mechanicsville,
Overbrook,
Quarries,
Greenboro,
Uplands,
Merivale], axis=0)

Ottawa_df.shape

(867, 13)

In [23]:
Ottawa_no_duplicates = Ottawa_df.drop_duplicates(subset=['Name', 'Categories', 'Cuisine Types', 'Nationalities','Address'])

In [24]:
Ottawa_no_duplicates.shape

(642, 13)

In [25]:
Ottawa_no_duplicates.reset_index(drop=True, inplace=True)
Ottawa_no_duplicates

,Name,Categories,Cuisine Types,Nationalities,Rating,Address,Res_Latitude,Res_Longitude,Reviews,Distance,Phone,Closed,Price
0,JOEY Lansdowne,"Canadian (New), Lounges, Steakhouses",Steakhouses,Canadian (New),4.0,"825 Exhibition Way, Ottawa",45.399658,-75.684106,126,916.293778,+16136955639,False,$$
1,The Belmont,"Tapas/Small Plates, Cocktail Bars",Cocktail Bars,,4.5,"1169 Bank Street, Ottawa",45.392288,-75.681671,29,213.095417,+16139793663,False,$$
2,Pelican Seafood Market & Grill,"Seafood, Seafood Markets","Seafood, Seafood Markets",,4.5,"1500 Bank Street, Ottawa",45.381098,-75.670445,139,1590.169444,+16135265229,False,$$
3,Oat Couture Oatmeal Cafe,"Breakfast & Brunch, Coffee & Tea, Cafes","Coffee & Tea, Cafes",,4.5,"1154 Bank Street, Ottawa",45.392990,-75.682840,30,192.848117,+16137376654,False,N/A
4,Stella Luna Gelato Cafe,"Ice Cream & Frozen Yogurt, Desserts, Cafes","Desserts, Cafes",,4.5,"1103 Bank St, Ottawa",45.393960,-75.682890,137,276.756860,+16135231116,False,$
...,...,...,...,...,...,...,...,...,...,...,...,...,...
637,Casa Dei Panini,"Sandwiches, Italian, Breakfast & Brunch",Sandwiches,Italian,4.5,"52 Antares Drive, Ottawa",45.330970,-75.710280,6,1697.461674,+16137232272,False,$
638,Bâton Rouge Steakhouse & Bar,"Steakhouses, Cocktail Bars, Seafood","Steakhouses, Cocktail Bars, Seafood",,2.5,"270 West Hunt Club Road, Ottawa",45.339579,-75.711016,29,1283.715061,+16132242570,False,$$$
639,50 Two Breakfast & Lunch,"Breakfast & Brunch, Sandwiches",Sandwiches,,4.5,"52 Antares Drive, Nepean",45.331038,-75.710362,8,1697.561799,+16137232272,False,N/A
640,Wing Hing Chinese Food,"Chinese, Imported Food",,Chinese,2.0,"2 Woodfield Drive, Nepean",45.337550,-75.726470,4,345.630674,+16137235511,False,$$
641,Thai Express,Thai,,Thai,3.5,"330 West Hunt Club Road, Ottawa",45.338467,-75.714920,6,964.592966,+16132248228,False,N/A

In [26]:
Ottawa_no_duplicates.to_csv('Ottawa.csv', index=False)

In [1]:
import pandas as pd
Ottawa1_df = pd.read_csv('../data/Ottawa.csv')

In [2]:
Ottawa1_df.head()

,Name,Categories,Cuisine Types,Nationalities,Rating,Address,Res_Latitude,Res_Longitude,Reviews,Distance,Phone,Closed,Price
0,JOEY Lansdowne,"Canadian (New), Lounges, Steakhouses",Steakhouses,Canadian (New),4.0,"825 Exhibition Way, Ottawa",45.399658,-75.684106,126,916.293778,1.613696e+10,False,$$
1,The Belmont,"Tapas/Small Plates, Cocktail Bars",Cocktail Bars,NaN,4.5,"1169 Bank Street, Ottawa",45.392288,-75.681671,29,213.095417,1.613979e+10,False,$$
2,Pelican Seafood Market & Grill,"Seafood, Seafood Markets","Seafood, Seafood Markets",NaN,4.5,"1500 Bank Street, Ottawa",45.381098,-75.670445,139,1590.169444,1.613527e+10,False,$$
3,Oat Couture Oatmeal Cafe,"Breakfast & Brunch, Coffee & Tea, Cafes","Coffee & Tea, Cafes",NaN,4.5,"1154 Bank Street, Ottawa",45.392990,-75.682840,30,192.848117,1.613738e+10,False,NaN
4,Stella Luna Gelato Cafe,"Ice Cream & Frozen Yogurt, Desserts, Cafes","Desserts, Cafes",NaN,4.5,"1103 Bank St, Ottawa",45.393960,-75.682890,137,276.756860,1.613523e+10,False,$

In [3]:
Ottawa1_df['Price'].fillna(method='ffill', inplace=True)
columns_to_fill = ['Nationalities','Phone','Categories']
Ottawa1_df[columns_to_fill] = Ottawa1_df[columns_to_fill].fillna('NA')


import pandas as pd
import numpy as np
def fill_cuisine(row):
    if pd.notnull(row['Cuisine Types']):
        return row['Cuisine Types']
    categories = row['Categories'].split(', ')
    if len(categories) > 0:
        return categories[0]
    return np.nan

# Apply the function to fill 'Cuisine Types'
Ottawa1_df['Cuisine Types'] = Ottawa1_df.apply(fill_cuisine, axis=1)

Ottawa1_df['Phone'] = pd.to_numeric(Ottawa1_df['Phone'], errors='coerce').fillna(np.nan).astype('Int64').astype(str)

Ottawa1_df['City']='Ottawa'
# Print the updated DataFrame
Ottawa1_df.head()

,Name,Categories,Cuisine Types,Nationalities,Rating,Address,Res_Latitude,Res_Longitude,Reviews,Distance,Phone,Closed,Price,City
0,JOEY Lansdowne,"Canadian (New), Lounges, Steakhouses",Steakhouses,Canadian (New),4.0,"825 Exhibition Way, Ottawa",45.399658,-75.684106,126,916.293778,16136955639,False,$$,Ottawa
1,The Belmont,"Tapas/Small Plates, Cocktail Bars",Cocktail Bars,NA,4.5,"1169 Bank Street, Ottawa",45.392288,-75.681671,29,213.095417,16139793663,False,$$,Ottawa
2,Pelican Seafood Market & Grill,"Seafood, Seafood Markets","Seafood, Seafood Markets",NA,4.5,"1500 Bank Street, Ottawa",45.381098,-75.670445,139,1590.169444,16135265229,False,$$,Ottawa
3,Oat Couture Oatmeal Cafe,"Breakfast & Brunch, Coffee & Tea, Cafes","Coffee & Tea, Cafes",NA,4.5,"1154 Bank Street, Ottawa",45.392990,-75.682840,30,192.848117,16137376654,False,$$,Ottawa
4,Stella Luna Gelato Cafe,"Ice Cream & Frozen Yogurt, Desserts, Cafes","Desserts, Cafes",NA,4.5,"1103 Bank St, Ottawa",45.393960,-75.682890,137,276.756860,16135231116,False,$,Ottawa

In [4]:
print(Ottawa1_df.isnull().sum())

Name             0
Categories       0
Cuisine Types    0
Nationalities    0
Rating           0
Address          0
Res_Latitude     0
Res_Longitude    0
Reviews          0
Distance         0
Phone            0
Closed           0
Price            0
City             0
dtype: int64

In [5]:
Ottawa1_df['Res_Latitude'] = Ottawa1_df['Res_Latitude'].round(6)
Ottawa1_df['Res_Longitude'] = Ottawa1_df['Res_Longitude'].round(6)
Ottawa1_df['Distance']=Ottawa1_df['Distance'].round(2)

In [6]:
Ottawa1_df

,Name,Categories,Cuisine Types,Nationalities,Rating,Address,Res_Latitude,Res_Longitude,Reviews,Distance,Phone,Closed,Price,City
0,JOEY Lansdowne,"Canadian (New), Lounges, Steakhouses",Steakhouses,Canadian (New),4.0,"825 Exhibition Way, Ottawa",45.399658,-75.684106,126,916.29,16136955639,False,$$,Ottawa
1,The Belmont,"Tapas/Small Plates, Cocktail Bars",Cocktail Bars,NA,4.5,"1169 Bank Street, Ottawa",45.392288,-75.681671,29,213.10,16139793663,False,$$,Ottawa
2,Pelican Seafood Market & Grill,"Seafood, Seafood Markets","Seafood, Seafood Markets",NA,4.5,"1500 Bank Street, Ottawa",45.381098,-75.670445,139,1590.17,16135265229,False,$$,Ottawa
3,Oat Couture Oatmeal Cafe,"Breakfast & Brunch, Coffee & Tea, Cafes","Coffee & Tea, Cafes",NA,4.5,"1154 Bank Street, Ottawa",45.392990,-75.682840,30,192.85,16137376654,False,$$,Ottawa
4,Stella Luna Gelato Cafe,"Ice Cream & Frozen Yogurt, Desserts, Cafes","Desserts, Cafes",NA,4.5,"1103 Bank St, Ottawa",45.393960,-75.682890,137,276.76,16135231116,False,$,Ottawa
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
637,Casa Dei Panini,"Sandwiches, Italian, Breakfast & Brunch",Sandwiches,Italian,4.5,"52 Antares Drive, Ottawa",45.330970,-75.710280,6,1697.46,16137232272,False,$,Ottawa
638,Bâton Rouge Steakhouse & Bar,"Steakhouses, Cocktail Bars, Seafood","Steakhouses, Cocktail Bars, Seafood",NA,2.5,"270 West Hunt Club Road, Ottawa",45.339579,-75.711016,29,1283.72,16132242570,False,$$$,Ottawa
639,50 Two Breakfast & Lunch,"Breakfast & Brunch, Sandwiches",Sandwiches,NA,4.5,"52 Antares Drive, Nepean",45.331038,-75.710362,8,1697.56,16137232272,False,$$$,Ottawa
640,Wing Hing Chinese Food,"Chinese, Imported Food",Chinese,Chinese,2.0,"2 Woodfield Drive, Nepean",45.337550,-75.726470,4,345.63,16137235511,False,$$,Ottawa
641,Thai Express,Thai,Thai,Thai,3.5,"330 West Hunt Club Road, Ottawa",45.338467,-75.714920,6,964.59,16132248228,False,$$,Ottawa

In [7]:
Ottawa1_df.to_csv('../data/Ottawa.csv', index=False)

In [8]:
Ottawa1_df.to_excel('../data/Ottawa.xlsx', index=False)